### PR TITLE
feat: Spotlight integration with hydration-overlay

### PR DESCRIPTION
**Pull request by Shubhdeep12**
Feature Addition: Spotlight Integration in Hydration-Overlay

This pull request introduces an integration of Spotlight into the hydration-overlay module.

Key Highlights:
- Addressed all necessary conditions outlined in the discussion [here](https://github.com/BuilderIO/hydration-overlay/issues/40#issuecomment-1915056436).
- Note: Current integration and tests may not function as expected due to pending integration support in Spotlight. The implementation is primed for action once the necessary changes are merged.

Next Steps:
- Track the progress of Hydration-overlay integration in Spotlight [here](https://github.com/getsentry/spotlight/pull/343).
- Upon completion of Spotlight integration, a simple version update for the Spotlight package in this repository is all that's needed.

### CODE REVIEW

**Comment by Shubhdeep12** [comment]
Hi @samijaber, we are done here. 
we published a new version in spotlight to support hydration-overlay.
Added a test case also for nextjs app.

Please review.

Thanks.

btw, I found a issue while setting up webpack in nextjs with hydation-overlay but that will not hamper anything here. 
I'll open it seperately.

**Comment by Shubhdeep12** [comment]
Hi @samijaber just bumping here for this PR.

Thanks.

**Comment by Shubhdeep12** [comment]
Hi @samijaber  just nudging for this feature.
Can you please review this PR.
Thanks

**Comment by Shubhdeep12** [comment]
Hi @samijaber just bunping here as a reminder for this PR.
Thanks

**Review by samijaber — APPROVED** [review]
Thanks for the PR @Shubhdeep12! And thanks for your patience until we got around to reviewing this 🙏🏽

**Pull request merged**
